# eslint@~2.2.0
# @see http://eslint.org/docs/rules
# When adding rules, be sure to sort them, e.g. vim :'<,'>sort
root: true
rules:
  ##### Possible Errors #####
  no-console: 'warn'
  no-debugger: 'warn'
  no-dupe-args: 'error'
  no-dupe-keys: 'error'
  no-duplicate-case: 'error'
  no-empty-character-class: 'error'
  no-ex-assign: 'error'
  no-extra-boolean-cast: 'warn'
  no-extra-semi: 'warn'
  no-func-assign: 'warn'
  no-inner-declarations: 'error'
  no-invalid-regexp: 'error'
  no-irregular-whitespace: 'warn'
  no-negated-in-lhs: 'error'
  no-regex-spaces: 'warn'
  no-sparse-arrays: 'warn'
  no-unexpected-multiline: 'error'
  no-unreachable: 'warn'
  use-isnan: 'error'
  valid-typeof: 'error'

  ##### Best Practices #####
  dot-notation: 'warn'
  eqeqeq: ['error', 'smart'] # fixable
  no-alert: 'warn'
  no-caller: 'warn'
  no-eval: 'error'
  no-extend-native: 'error'
  no-extra-bind: 'warn'
  no-floating-decimal: 'error'
  no-iterator: 'error'
  no-labels: 'error'
  no-loop-func: 'warn'
  no-multi-spaces: 'warn' # fixable
  no-native-reassign: 'error'
  no-octal: 'error'
  no-proto: 'error'
  no-redeclare: 'error'
  no-sequences: 'error'
  no-unused-expressions: 'warn'
  no-with: 'error'

  ##### Variables #####
  no-delete-var: 'error'
  no-shadow-restricted-names: 'error'
  no-undef-init: 'warn'
  no-undef: 'error'
  no-unused-vars: ['warn', {args: 'all', argsIgnorePattern: '^_'}]
  no-use-before-define: ['error', 'nofunc']

  ##### Stylistic Issues #####
  array-bracket-spacing: 'warn' # fixable
  block-spacing: 'warn' # fixable
  brace-style: ['warn', 'stroustrup', {allowSingleLine: true}]
  func-style: ['warn', 'declaration', {allowArrowFunctions: true}]
  indent: ['warn', 'tab', {SwitchCase: 0}] # fixable
  key-spacing: 'warn'
  keyword-spacing: 'warn' # fixable
  new-parens: 'warn'
  no-mixed-spaces-and-tabs: 'warn'
  no-spaced-func: 'warn' # fixable
  no-unneeded-ternary: ['warn', {defaultAssignment: false}]
  object-curly-spacing: 'warn' # fixable
  one-var-declaration-per-line: 'warn'
  operator-linebreak: ['warn', 'before', {overrides: {'=': 'after'}}]
  quotes: ['warn', 'single', 'avoid-escape'] # fixable
  semi: ['warn', 'always'] # fixable
  space-before-function-paren: ['warn', {anonymous: 'always', named: 'never'}] # fixable
  space-in-parens: 'warn'
  space-infix-ops: 'warn' # fixable
  space-unary-ops: 'warn' # fixable

  #### ECMAScript 6 ####
  no-class-assign: 'warn'
  no-const-assign: 'warn'
  no-dupe-class-members: 'warn'
